version: '3.8'

services:
  text-to-text:
    image: text-to-text
    build:
      context: ../text-to-text
      dockerfile: Dockerfile
    volumes:
      - ./data/text-to-text/input:/input # Wird von GUI angelegt, enthält slides.pptx
      - ./data/text-to-text/output:/output # Legt slide_X.txt ab
    env_file: run.env

  avatar-generation:
    image: avatar-generation
    build:
      context: ../avatar-generation
      dockerfile: Dockerfile
    volumes:
      - ./data/avatar-generation/input:/input # Wird von GUI angelegt, enthält Prompt für Avatar als avatar.txt
      - ./data/avatar-generation/output:/output # Legt avatar.png ab
    env_file: run.env

  text-to-speech:
    image: text-to-speech
    build:
      context: ../voice-cloning/TTS_VC_english
      dockerfile: Dockerfile
    depends_on:
      text-to-text:
        condition: service_completed_successfully
    volumes:
      - ./data/text-to-speech/input:/input # Enthält voice.mp3
      - ./data/text-to-text/output:/input/ttt # Enthält slide_X.txt von text-to-text
      - ./data/text-to-speech/output:/output # Legt audio_X.wav ab

  lip-sync:
    image: lip-sync
    build:
      context: ../lip-sync
      dockerfile: Dockerfile
    depends_on:
      text-to-speech:
        condition: service_completed_successfully
      avatar-generation:
        condition: service_completed_successfully
    volumes:
      - ./data/avatar-generation/output:/input # Enthält avatar.png
      - ./data/text-to-speech/output:/input/tts # Enthält audio_X.wav von text-to-speech
      - ./data/lip-sync/output:/output # Legt video_X.mp4 ab
  
  video-generation:
    image: video-generation
    build:
      context: ../create-video
      dockerfile: Dockerfile
    depends_on:
      lip-sync:
        condition: service_completed_successfully
    volumes:
      - ./data/video-generation/input:/input # Wird von GUI angelegt, enthält slides.pptx
      - ./data/lip-sync/output:/input/ls # Enthält video_X.mp4 von lip-sync
      - ./data/video-generation/output:/output # Legt video.mp4 ab

# Output von video generation umbennen in slide Titel und in cwd verschieben
