# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./avatar-generation /app

# Create /app/avatar directory
RUN mkdir /app/avatar

# Install the dependencies
COPY avatar-generation/requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

# Run main.py when the container launches
CMD ["python", "main.py"]
